### ISSUE TITLE
Problem when using `oj` as JSON library.

### ISSUE THREAD

**Issue by seban** [pact-foundation/pact-ruby#166]
[oj](https://github.com/ohler55/oj)  is A fast JSON parser and Object marshaller as a Ruby gem. I tried to used it in my Rails application but looks like pact tests are failing when `oj` is used as default parser/marshaller. 
I have posted an inssue in `oj` gem already - https://github.com/ohler55/oj/issues/475. Now JSON representation looks ok, but rspec is still failing and it looks like more work than that is required. 
I created also sample https://github.com/seban/oj-pact-problem rails (4.2.10) app to reproduce conditions. 
Can some one advise me on this one?

**Comment by bethesque** [comment]
Firstly, thank you for creating a repository for recreating the issue! It makes life so much easier, and it's so rarely done. I really appreciate it.

So, as you've observed, the problem is caused by the fact that OB serialises Regexp differently to standard JSON. 

```
"(?-mix:application\\/json)"}}}}
```

I've had this problem before with ActiveSupport, and had to resort to some dodgey dodgey hacks to make it work. I'll see if I can do the same to make it work with OJ.

**Comment by seban** [comment]
@ohler55 make some branch where he tries to fix it on `oj` side also. Probably worth checking

**Comment by seban** [comment]
Any update on this one? Can I help you somehow?

**Comment by ohler55** [comment]
I think it was resolved. Oj was using the default for Rails instead of for the JSON gem. Now it does both according to the mode.

**Comment by bethesque** [comment]
Sorry, I got confused and thought the other issue that got closed (https://github.com/pact-foundation/pact-ruby/issues/169) was this one. Is it still an issue?

**Comment by seban** [comment]
I still have a the same problem. Test passes as long as I don't use `Pact.like`.
I attached the log:
[zoo_mock_service.log](https://github.com/pact-foundation/pact-ruby/files/2108231/zoo_mock_service.log)

**Comment by ohler55** [comment]
@bethesque can you explain? Is it in the Pact code?

**Comment by bethesque** [comment]
I'm so sorry, I forgot about this.

The problem is occurring at this line of code, where the incoming JSON should be loaded into Ruby classes.

```
# lib/pact/mock_service/request_handlers/interaction_post.rb

interaction = Interaction.from_hash(JSON.load(request_body))
```

#### Without OJ

A `Pact::SomethingLike` is correctly made.

```
I, [2018-07-10T07:27:25.723163 #70020]  INFO -- : #<Pact::QueryHash:0x007ffb3ab67d70 @hash={:q=>[#<Pact::SomethingLike:0x007ffb3ab6e698 @contents="gator">]}>
```

#### With OJ

The hash stays as a hash, and does not get loaded into a `Pact::SomethingLike`.

```
I, [2018-07-10T07:42:21.529658 #70049]  INFO -- : #<Pact::QueryHash:0x007f9f05ced528 @hash={:q=>[{"json_class"=>"Pact::SomethingLike", "contents"=>"gator"}]}>
```

I'm guessing OJ uses a different technique for recognising and loading embedded Ruby classes in JSON.

**Comment by bethesque** [comment]
I've narrowed down the problem to this failing test: https://github.com/bethesque/oj-pact-problem/commit/63cfd072e7232fc8877c4ccfe71c4cfee7b5b1e8

If you run it with `OJ_ENABLED=true`, it fails.

```ruby
  1) Pact::SomethingLike JSON.load creates a SomethingLike object from json
     Failure/Error: expect(subject).to eq(SomethingLike.new({"thing" => "blah"}))

       expected: #<Pact::SomethingLike:0x007faf5215ecb8 @contents={"thing"=>"blah"}>
            got: {"json_class"=>"Pact::SomethingLike", "contents"=>{"thing"=>"blah"}}

       (compared using ==)

       Diff:
       @@ -1,2 +1,3 @@
       -#<Pact::SomethingLike:0x007faf5215ecb8 @contents={"thing"=>"blah"}>
       +"contents" => {"thing"=>"blah"},
       +"json_class" => "Pact::SomethingLike",

     # ./spec/models/something_like_spec.rb:23:in `block (3 levels) in <module:Pact>'
```

**Comment by ohler55** [comment]
That's helpful. Oj will honor the `json_class` with the appropriate options set. If `Oj.mimic_JSON` was called the option should already be set. If not then setting the `create_id` to `json_class` should do the trick. Do you know what the options are?

```ruby
puts Oj.default_options
```

**Comment by bethesque** [comment]
```
{:indent=>0, :second_precision=>9, :circular=>false, :class_cache=>true, :auto_define=>false, :symbol_keys=>false, :bigdecimal_as_decimal=>nil, :use_to_json=>false, :use_to_hash=>false, :use_as_json=>false, :nilnil=>false, :empty_string=>true, :allow_gc=>true, :quirks_mode=>true, :allow_invalid_unicode=>false, :allow_nan=>true, :trace=>false, :float_precision=>16, :mode=>:object, :escape_mode=>:json, :time_format=>:unix, :bigdecimal_load=>:auto, :create_id=>"json_class", :space=>nil, :space_before=>nil, :object_nl=>nil, :array_nl=>nil, :nan=>:auto, :omit_nil=>false, :hash_class=>nil, :array_class=>nil, :ignore=>nil}
```

**Comment by bethesque** [comment]
It looks ok to me 🤔

**Comment by ohler55** [comment]
Oj is in `:object` mode. That's great for serializing and de-serializing as long as no other components are involved but in this case I think either the `:compat` mode or the `:custom` mode would be better. If you want Oj to be like the JSON gem then call `Oj.mimic_JSON`. I noticed that `:use_to_json` is also false which is probably not what you want.

**Comment by bethesque** [comment]
I cannot fix the error with any value of `mode` that I've tried. eg. `Oj.default_options = {:mode => :compat }`

**Comment by ohler55** [comment]
Can you call `Oj.mimic_JSON`?

**Comment by bethesque** [comment]
It doesn't fix it. The only thing that makes it work is taking away the `Oj.optimize_rails` call, and then I don't need to do anything else.

**Comment by ohler55** [comment]
That is odd although rails and the JSON do fight over encoding. In then end, the setting that `Oj.mimic_JSON` sets up are probably what you want. There are a few options that are changed in order to mimic the JSON gem. Calling `Oj.optimize_rails` after that will change some of them and also change the way `to_json` works so that it is like rails instead of the JSON gem.

**Comment by ohler55** [comment]
Do you have a test setup I can use to put together a set of options that will do what you want?

**Comment by bethesque** [comment]
Yes, you can clone this: https://github.com/bethesque/oj-pact-problem

**Comment by ohler55** [comment]
Okay, thanks. Will look into it tomorrow.

**Comment by ohler55** [comment]
Adding `create_additions: true` to the default options fixed the issue but I noticed that does not show up in the default options so that needs to be fixed. The kicker is that in the older JSON gem the `create_additions` defaulted to true. In the more recent that Oj is mimicking it is set to false. To be on the safe side you should explicitly set that since the default can not be counted on being the same from one version to the next.

**Comment by bethesque** [comment]
Thanks @ohler55. 

As a summary for future users with the same problem, if you're using Pact with OJ and you call `Oj.optimize_rails`, you also need to call `Oj.default_options = { create_additions: true}`.

@seban this is a change that I think belongs in your codebase rather than in the Pact code, so I'm going to close this issue now.

**Comment by ohler55** [comment]
I was nice working with you on this. Thanks.

**Comment by bethesque** [comment]
Thanks for your help @ohler55

**Comment by bheemreddy181** [comment]
@bethesque I am still facing the same issue even after adding ```Oj.default_options = { create_additions: true }```

**Comment by bheemreddy181** [comment]
@bethesque you can ignore my comment as per https://github.com/ohler55/oj/issues/532
